
app:
  network:
    host: ''
    password: ''
    port: 0
    type: No Proxy
    username: ''
  style:
    theme: 'Bright'

classifications:
  genotypes: 
  - number: 0
    description: "To confirm"
    name: "To confirm"
    color: 'dimgray'
  - number: 1
    description: "Confirmed"
    name: "confirmed"
    color: 'green'

  samples: 
  - number: -1
    description: "Sample is canceled "
    name: "Rejected"
    color: 'dimgray'
  - number: 0
    description: "Sample is not valided "
    name: "Pending"
    color: 'orange'
  - number: 1
    description: "Sample valided"
    name: "Valided"
    color: 'green'

  variants:
  - number: -1
    description: "Rejected or artifact"
    name: Rejected
    color: '#dimgray'
  - number: 0
    description: "Unclassified"
    name: "Unclassified"
    color: '#lightgray'
  - number: 1
    description: "Benin"
    name: "Benin"
    color: '#71e096'
  - number: 2
    description: "Likely benin"
    name: "Likely benin"
    color: '#71e096'
  - number: 3
    description: "Variant of uncertain significance"
    name: "Variant of uncertain significance"
    color: '#f5a26f'
  - number: 4
    description: "Likely pathogenic"
    name: "Likely pathogenic"
    color: '#ed6d79'
  - number: 5
    description: "Pathogenic"
    name: "Pathogenic"
    color: '#ed6d79'

tags:
  genotypes:
  - color: '#144eff'
    description: tag2
    name: genotype#tag2
  - color: '#ff343e'
    description: tag1
    name: genotype#tag1
  samples:
  - color: '#3251ff'
    description: tag2
    name: sample#tag2
  - color: '#ff3932'
    description: tag1
    name: sample#tag1
  variants:
  - color: '#ff201e'
    description: tag1
    name: variant#tag1
  - color: '#2e3dff'
    description: tag2
    name: variant#tag2


variant_view:
  memory_cache: 32
  rows_per_page: 50
  links:
    - name: "GenCards - The human gene database"
      is_browser: true
      is_default: false
      url: "https://www.genecards.org/cgi-bin/carddisp.pl?gene={{annotations[0].gene}}"
    - name: "Varsome - Genes"
      is_browser: true
      is_default: false
      url: "https://varsome.com/gene/{{annotations[0].gene}}"
    - name: "Varsome - Variants"
      is_browser: true
      is_default: false
      url: "https://varsome.com/variant/hg19/{{chr|replace('chr','')}}-{{pos}}-{{ref}}-{{alt}}"
    - name: "Google - Gene"
      is_browser: true
      is_default: false
      url: "https://google.com/search?q={{annotations[0].gene}}"
    - name: "Google - Gene ID"
      is_browser: true
      is_default: false
      url: "https://google.com/search?q={{annotations[0].gene_id}}"
    - name: "dbSNP"
      is_browser: true
      is_default: false
      url: "https://www.ncbi.nlm.nih.gov/snp/{{rs}}"
    - name: "Clinvar - Allele ID"
      is_browser: true
      is_default: false
      url: "http://www.ncbi.nlm.nih.gov/clinvar/?term={{alleleid}}[alleleid]"
    - name: "IGV"
      is_browser: false
      is_default: false
      url: "http://localhost:60151/goto?locus=chr{{chr|replace('chr','')}}:{{pos}}"
    - name: "UCSC hg38"
      is_browser: true
      is_default: false
      url: "https://genome.ucsc.edu/cgi-bin/hgTracks?db=hg38&position={{chr}}:{{pos}}"
    - name: "UCSC hg19"
      is_browser: true
      is_default: false
      url: "https://genome.ucsc.edu/cgi-bin/hgTracks?db=hg19&position={{chr}}:{{pos}}"
    - name: "UCSC hg38"
      is_browser: true
      is_default: false
      url: "https://genome.ucsc.edu/cgi-bin/hgTracks?db=hg38&position={{chr}}:{{pos}}"
    - name: "Ensembl GRCh38"
      is_browser: true
      is_default: false
      url: "https://www.ensembl.org/Homo_sapiens/Location/View?r={{chr}}:{{pos}}-{{pos}}"
    - name: "Ensembl GRCh37"
      is_browser: true
      is_default: false
      url: "http://grch37.ensembl.org/Homo_sapiens/Location/View?r={{chr}}:{{pos}}-{{pos}}"
