name: CI 

# when it active ? 
on: 
  push:
    branches:
      - github-ci 


jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: install_deps
        run: "make install_deps"
      - name: make test 
        run "make test"